apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: template-typescript-react
build:
  artifacts:
    - image: template-typescript-react/node
  tagPolicy:
    sha256:
    gitCommit:
      variant: AbbrevCommitSha
  local:
    push: false
    useBuildkit: true
    concurrency: 0
