apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: template-typescript-react-ant
build:
  tagPolicy:
    sha256: {}
  local:
    concurrency: 0
    useBuildkit: true
    push: false
    useDockerCLI: false
  artifacts:
  - image: nginx

