name: Infrastructure provision
on: [push]
env:
  DIGITALOCEAN_API_TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
defaults:
  run:
    working-directory: cloud
jobs:
  terraform:
    name: Terraform cloud infrastructure
    env:
      TF_VAR_digitalocean_api_token: $DIGITALOCEAN_API_TOKEN
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13-beta1
      - name: Initialize modules
        run: terraform init
      - name: Validate syntax
        run: terraform validate
      - name: Plan required changes
        run: terraform plan -input=false
      - name: Apply plans
        run: terraform apply -input=false -auto-approve
  helm:
    name: Deploy Helm charts
    runs-on: ubuntu-latest
    needs:
      - terraform
      - api-image
      - web-image
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Setup Helm
        uses: mamezou-tech/setup-helmfile@v0.2.4
        with:
          helmfile-version: v0.118.7
          helm-version: v3.2.3
          kubectl-version: v1.18.0
      - name: Install Helm diff plugin
        run: helm plugin install https://github.com/databus23/helm-diff --version master
      - name: Create Kubernetes CRDs
        run: helm upgrade --install --cleanup-on-fail --atomic crds charts/crds
      - name: Deploy Helm charts
        run: helmfile apply
        env:
          GRAFANA_ADMIN_PASSWORD: ${{ secrets.grafana_admin_password }}
