name: Production
on:
  push:
    tags:
      - 'v*'
jobs:
  version:
    name: Create versioned release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Get last release version
        id: released
        run: 'echo ::set-output tag=$(git describe --tags --abbrev=0)'
      - name: Get commits history between versions
        id: history
        run: 'echo ::set-output log=$(git log --date=format:"%Y-%m-%d" --pretty=format:"%h %cN %s" ${{ steps.released.outputs.tag }}..HEAD)'
      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          body: |
            # Release notes
            ${{ steps.history.outputs.log }}
  docker-service:
    name: Docker service update
    runs-on: ubuntu-20.04
    needs: [ version ]
    steps:
      - name: Trigger Docker service update
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: server.com
          username: root
          key: ${{ secrets.PRIVATE_KEY }}
          script: docker service update --with-registry-auth --image=${{ github.repository }}/node:latest react-app
